### PR TITLE
Upgrade to PostgreSQL 9.4.1

### PR DESCRIPTION
**Pull request by fancyremarker**

### CODE REVIEW

**Comment by chrisvariety** [comment]
What's the status of this? Would love to see support for 9.4.

**Comment by fancyremarker** [comment]
Rebased this, and upgraded to 9.4.2 (official Debian release got bumped since the PR was opened). Merging.

**Comment by fancyremarker** [comment]
@chrisvariety: Just merged and released as the default for new Aptible PostgreSQL databases.

**Comment by chrisvariety** [comment]
@fancyremarker Thanks!!!! :100:

**Pull request merged**
