### PR TITLE
Docker compose support: Conditionally initialize database on first start

### PR DESCRIPTION
**Pull request by polotek**
Before this update, db initialization was separate step accessed by
passing the --initialize flag to the run script. This still works.
But the initialize method has been made idempotent (probably) and
now runs before the server startup as well. This is helpful when we
want to use these containers with something like docker-compose,
where a separate initialization step isn't practical. Note that a
passphrase must be set and will be pulled from the PASSPHRASE env
variable. This must be passed in when using docker-compose.

### CODE REVIEW

**Comment by polotek** [comment]
With this change, I was able to get our multi-container environment running locally with docker compose. Here's a simplified example. Note that devs need to provide the `.aptible.env` file locally with any necessary environment variables.

```yaml
version: "2"
services:
    api_service:
        container_name: api_service
        build: .
        env_file: .aptible.env
        entrypoint: python3 src/python/api_service.py --port 8080
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        links:
            - dev_app_db
    dev_app_db:
        image: quay.io/aptible/postgresql:latest
        environment:
            - PASSPHRASE=password
        ports:
            - "15432:5432"
        volumes:
            - dev_app_db-data:/var/db
volumes:
    dev_app_db-data: {}
```

**Comment by krallin** [comment]
Hey @polotek, thanks for taking the time to contribute.

I'm a little unsure about this idea for a couple of reasons:

+ This would tend to silently hide errors where a DB is launched without having been initialized first (which could be symptomatic of e.g. the orchestrator not properly reusing a data volume — something we wouldn't want to silently ignore). It might also tend to make tests pass when they should fail (I fixed a similar issue in our ES image recently).
+ Making this change here may (eventually) create an expectation that skipping `--initialize` is fine for all Aptible DB images (which it isn't right now) 

I also have a couple of reservations implementation-wise:

+ We're not testing this path works, so there's little guarantee it won't eventually break (if e.g. we add an additional initialization step and forget to add it there). 
+ It seems like we're only "re-initializing" for the server case, but not the read-only one. Why not?

--

If your goal is to initialize and launch the DB in just one step, have you considered overriding the entrypoint with `bash` and running both steps?

IMHO, this would create less of a maintenance burden. Here's how you might go about doing it with Compose:

```
dev_app_db:
  image: quay.io/aptible/postgresql:latest
  entrypoint: bash
  command: -c 'run-database.sh --initialize && run-database.sh'
  environment:
    - PASSPHRASE=password
```

Let me know whether you think that might work for you (and if not, why)

Thanks!

**Comment by polotek** [comment]
These are all good questions. This is only a first pass and I don't have
all of the context around why the run script is set up the way it is. I'll
try to address some of your questions.

First off, the reason I thought this might be an appropriate approach is
that I think it's the one I see the docker community recommending. Many
docker images for databases tend to support automatic initialization on
first startup. I think this is exactly because there is no initialization
step supported in the container lifecycle. I would rather it be a separate
addressable step as well. I'm looking to see if this question has been
raised in the docker community.

Here are some references I took a look at.

mysql -
https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance
postgres -
https://github.com/docker-library/docs/tree/master/postgres#how-to-extend-this-image
<https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance>

As for my implementation, I definitely want to get feedback on whether it's
any good. In particular, I'm not comfortable with the guard on the
pg_init_auth function. It just checks whether there are any files in the
data dir. I stole this from other scripts I had seen.

* Specifically, this from convox.
https://github.com/convox/postgres/blob/master/docker-entrypoint.sh#L4
* There's also the way the official docker image handles it. By checking
for `PG_VERSION`,
https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L18

Other replies inline.

On Sun, Feb 28, 2016 at 10:08 AM Thomas Orozco <notifications@github.com>
wrote:

>
>    - This would tend to silently hide errors where a DB is launched
>    without having been initialized first (which could be symptomatic of e.g.
>    the orchestrator not properly reusing a data volume — something we wouldn't
>    want to silently ignore). It might also tend to make tests pass when they
>    should fail (I fixed a similar issue in our ES image recently).
>
> I'm not sure I understand this. If the pg_init_auth fails, it would fail
the launch right? Unless you're talking about trying to launch a db where
the init check above passes, even though it hasn't been properly
initialized. I'd like to hear more about that edge case.

>
>    - Making this change here may (eventually) create an expectation that
>    skipping --initialize is fine for all Aptible DB images (which it
>    isn't right now)
>
> Yes I expect that if this approach is accepted, this support will have to
be extended to all aptible storage images. I understand that's a burden.
But I'd be willing to help with it. I expect this would one part of a more
comprehensive rollout of docker-compose support.

> I also have a couple of reservations implementation-wise:
>
>    - We're not testing this path works, so there's little guarantee it
>    won't eventually break (if e.g. we add an additional initialization step
>    and forget to add it there).
>
> The initialization is wrapped in a function, `pg_init_auth`. I assume any
additions would go there. It's shared between the `--initialize` path and
the main startup path. Am I missing something about what you're saying
here? I'm willing to add more tests if you let me know what you think that
looks like.

>
>    - It seems like we're only "re-initializing" for the server case, but
>    not the read-only one. Why not?
>
> Yeah here's where I'm missing context. If you help me understand the
purpose of the other paths in the run script a little better, I can extend
the support.

>
>
> If your goal is to initialize and launch the DB in just one step, have you
> considered overriding the entrypoint with bash and running both steps?
>
This is totally reasonable of course. But the `--initialize` branch would
still need to be made idempotent. docker-compose wants to be able to spin
containers up and down if it needs to.

> IMHO, this would create less of a maintenance burden. Here's how you might
> go about doing it with Compose:
>
Can you expand on the maintenance burden you're referring to? I want to
make sure I understand.

Thanks for all the input. I hope this helps clarify my intent.

>

**Comment by krallin** [comment]
Hey @polotek, I'm sincerely sorry about the delay in getting back to you; we've been discussing this internally with @fancyremarker .

First, I'd like to respond to your latest comments:

> First off, the reason I thought this might be an appropriate approach is
> that I think it's the one I see the docker community recommending. Many
> docker images for databases tend to support automatic initialization on
> first startup. I think this is exactly because there is no initialization
> step supported in the container lifecycle. I would rather it be a separate
> addressable step as well. I'm looking to see if this question has been
> raised in the docker community.

You're correct that containers don't have a separate initialization step in Docker (and that makes sense). However, on Aptible, we do start databases in two steps (first we run `--initialize`, then we run without any args, which starts the server).

Now, we *could* discuss the respective merits of doing so. One the benefits for us is that our DB containers don't need to be aware of whether they need to initialize again (i.e. that responsibility is pushed to the container orchestration). Regardless, I don't think we want to prioritize changing this right now (it's a lot of effort, and doesn't seem like the best solution to the problem).

> >    - This would tend to silently hide errors where a DB is launched
> >    without having been initialized first (which could be symptomatic of e.g.
> >    the orchestrator not properly reusing a data volume — something we wouldn't
> >    want to silently ignore). It might also tend to make tests pass when they
> >    should fail (I fixed a similar issue in our ES image recently).
> 
> I'm not sure I understand this. If the pg_init_auth fails, it would fail
> the launch right? Unless you're talking about trying to launch a db where
> the init check above passes, even though it hasn't been properly
> initialized. I'd like to hear more about that edge case.

I was talking from our perspective as users of those databases. As it turns out, we ran into this exact issue a couple days after I posted this comment. Here a (simplified) recap of what happened:

- I refactored the way we launch database containers
- I made a mistake in the implementation of DB cloning (forgot to `--initialize` the database). 
- Our cloning tests passed.
- Frank tried to clone a Postgres DB in our staging environment, and it failed because the DB had never been initialized.

As it turns out, our cloning tests used our Redis image, which (I'm not sure why it's that way) doesn't fail it hasn't been initialized, and that's why the tests didn't fail. 

IOW, The Redis image does exactly what the PG image would do if it had the same issue, and that caused an actual error to not be apparent in tests.

Now, one could definitely argue that the Redis database behaves properly, and the PG image is the one that behaved incorrectly, but that takes me back to my earlier point: two-step DB startup may or may not be ideal, but I think it's a little late to change it now unless there's a substantial upside to doing so.

> > I also have a couple of reservations implementation-wise:
> >
> >    - We're not testing this path works, so there's little guarantee it
> >    won't eventually break (if e.g. we add an additional initialization step
> >    and forget to add it there).
> 
> The initialization is wrapped in a function, `pg_init_auth`. I assume any
> additions would go there. It's shared between the `--initialize` path and
> the main startup path.

That might be a bold assumption; I don't think I can trust future me making changes to this image to add non-auth-related things to a function called `pg_init_auth` (note: just like present you didn't add auth-related changes to  `pg_init_conf`, which is shared between the `--initialize` path and the main startup path).

I confess I'm being extremely conservative here. At this point you might even feel like I'm stonewalling you (and if so I apologize, that's not my intention). However, there's a large number of moving parts involved in standing up a DB on Aptible (PG is one of the simpler ones — look at MongoDB for a comparison), so as far as I'm concerned, if it's not tested, I'm eventually going to (inadvertently) break it. 

Hence my reluctance to just expect I would not eventually break it :)

> > If your goal is to initialize and launch the DB in just one step, have you
> > considered overriding the entrypoint with bash and running both steps?
> 
> This is totally reasonable of course. But the `--initialize` branch would
> still need to be made idempotent. docker-compose wants to be able to spin
> containers up and down if it needs to.

That's a good point. I'm sorry I didn't account for this in my earlier response! Here's an alternative command that does that:

```
docker run --rm -it --entrypoint bash -e PASSPHRASE=123 quay.io/aptible/postgresql -c 'set -ex && if [[ ! -f "/var/db/PG_VERSION" ]]; then run-database.sh --initialize; fi && run-database.sh'
```

> > IMHO, this would create less of a maintenance burden. Here's how you might
> > go about doing it with Compose:
>
> Can you expand on the maintenance burden you're referring to? I want to
> make sure I understand.

Sure. The maintenance burden is for us: we'd have to maintain something we're not really using (compose support) but which happens to be intertwined with other things we are in fact using (and thus might want to change).

--

As far as compose support is concerned (I fully agree with you it's desirable), I think we should consider an approach that's less intrusive (i.e. doesn't change the existing code).

Something like a `--compose` command that checks if `--initialize` is is needed and runs it if so, then starts the DB would (I think) work just as well with less potential for breakage:


For example:

```
# Disclaimer: I have *not* tested this yet, there might be typos, etc.
if [[ "$1" == "--compose" ]]; then
  if [[ ! -f "/var/db/PG_VERSION" ]]; then 
    "$0" --initialize
  fi
  exec "$0"
```

I would argue this is also more discoverable, but more importantly it's a lot easier to port to our other database images.

--

To summarize:

- I agree with you that supporting compose would make those images more useful.
- However, I'm concerned that making changes to the paths used outside of compose to accommodate compose will make those other paths more complex and more subject to breakage.
- Fortunately, I don't think we even *need to* make changes to those paths: we can provide compose support without touching any of those (either using an entrypoint as a temporary workaround, or by adding this functionality in the `run-database.sh` script).

For now, I'm going to close this PR. 

That's not because I disagree that there is a problem (you it clear that our images don't work well with compose and I agree); it's only because I think the approach proposed here makes sense in isolation but breaks down when we consider how we're using those images in Aptible itself (which of course I wouldn't have expected you to be aware of!).

Hope this makes sense. Just let me know what you think,

-- Thomas

**Comment by polotek** [comment]
Thanks @krallin. All of this makes sense. I think adding the `--compose` entrypoint is a reasonable compromise. If I submit the PR, would you accept it? It would be so much more convenient. I've been trying to incorporate the long init+start command you suggested above into my `docker-compose.yml` and it's very unwieldy.

**Pull request closed without merging**
